version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
          command: ruby app.rb
      - run:
          command: echo "export RUBY_TEXT='$(ruby app.rb)'" >> $BASH_ENV
      - run:
          command: echo "${RUBY_TEXT}"

workflows:
  build:
    jobs:
      - build
